# 00: Python Programming
## A. Welcome to Jupyter (a.k.a. Ipython Notebooks)
Take a while to adjust your bearings. Study the icons above. 

There are two major types of cells:

1) Markdown cells - simple text. One can do html tags like <b>BOLD</b> or latex like $\beta$.
Double click on a cell to see how a markdown is formatted.

2) Code cells - cells where we can run code.


<b>Shortcuts</b>

1) <b>CTRL-M/ESC</b> then <b>H</b> to see help

2) <b>CTRL-M/ESC</b> then <b>S</b> to save notebook

3) <b>CTRL-ENTER</b> to Run Code but stay in the same cell

4) <b>SHIFT-ENTER</b> to Run Code and advance to the next cell

5) Using <b>%pylab inline</b> preceeding everything else in the notebook imports already matplotlib and numpy. It also enables our graphics to be part of the notebook.

6) You can use <b>TAB</b> to see available functions. You can use <b>SHIFT-TAB</b> repeatedly for the documentation. You can put a <b>?</b> at the end or at the beginning of a command to load the documentation in a split pane.

In [1]:
3+4

7

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## B. Variables and Data Types

Python uses five standard data types:

### B.1 Numbers

In [2]:
varNum = 123
pi = 3.14159

In [5]:
print(varNum)
pi

123


3.14159

In [11]:
pi
type(pi)

float

varNum is an Integer, thus it does not handle numbers with decimal places while pi is a Float where values in the decimal place are handled.

### B.2 Strings

In [12]:
varString = "Hello World!"
varText = 'This is a String'
print(varString)
print("The length of varString is ", len(varString))

Hello World!
The length of varString is  12


In [7]:
len(varString)

12

Strings may be declared with a single quote (') or double quote ("), some even use triple double quotes("""). One may use them interchangeable but some prefer to follow a specific format.

### B.3 Lists

In [14]:
varList = ["abc", 123]
print(varList)
print(len(varList))
varList[0]

['abc', 123]
2


'abc'

You can think of Lists as similar to ArrayLists where the index starts at 0 and you can obtain the contents of a list by using brackets that contain the index of the element. You may also append items in the list and remove them as well.

### B.4 Tuples

In [17]:
varTuple = ('abc', 123, "HELLO")
print(varTuple)
print(len(varTuple))
print(varTuple[0])

print?

('abc', 123, 'HELLO')
3
abc


It may seem like there are no differences between Tuples and Lists other than Tuples use parenthesis while lists use brackets, but actually there are minor differences. For one thing, Tuples are fixed structures thus do not have the luxury of Lists to append or remove elements. Generally Lists have a lot of other functions readily available as opposed to using Tuples.

<b>HINT:</b> You can try to type <b><i>varList.</i></b> in one line as well as <b><i>varTuple.</i></b> and press <b>TAB</b> after the period (.) in order to view possible functions you can call from that variable. You may also try to press <b>CTRL + TAB</b> when the text cursor.

However Tuples actually use less space in the memory as opposed to Lists, resulting in faster processing. One thing to take note of is that one would usually use Tuples when the size of the contents are static as opposed to Lists where one can use it to continuously modify the size and elements.

In [22]:
print(varList)
print(varList.__sizeof__())
print(varTuple)
print(varTuple.__sizeof__())

['abc', 123]
56
('abc', 123, 'HELLO')
48


### B.5 Dictionaries

In [19]:
var = 3
varDict = {'first':1.23123, 
           '2':'2nd', 
           3.123:var}
varDict['2']

'2nd'

You may also declare contents of dictionaries individually

In [27]:
varDict = {}
varDict['first'] = 1
varDict['2'] = '2nd'
varDict[3] = var
print(varDict['2'])

2nd


In [28]:
varDict = {}
varDict["example"] = {"number1" : 1, "number2" : 2}
varDict

{'example': {'number1': 1, 'number2': 2}}

If you have experience in using JavaScript Object Notation or JSON, Python's implementation of Dictionaries are quite similar to that. You may reference an element by inserting the label of the keypair.

## C. Arithmetic

Python uses basic arithmetic functions which are normally present on most if not all programming languages.

### Addition

In [29]:
a = 5 + 3
a

8

### Subtraction

In [30]:
a = 5 - 3
a

2

### Multiplication

In [31]:
a = 5 * 3
a

15

### Exponent

In [32]:
a = 5 ** 3
a

125

### Division

In [21]:
a = 5 / 3
a

1.6666666666666667

### Modulus Division

In [34]:
a = 5 % 3
a

2

### Integer Division

In [35]:
a = 5 // 3
a

1

### Increment

In [36]:
a = 5
a += 1
a

6

### Decrement

In [37]:
a = 5
a -= 1
a

4

<b>NOTE:</b> Python does not support the increment/decrement syntax of <b>x++/x--</b> instead you may use the syntax of <b>x+=1/x-=1</b> which is similar to <b>x=x+1/x=x-1</b>

### String Concatenation

In [38]:
a = 'Hello ' + 'World!'
a

'Hello World!'

Strings may also be appended with the use of the plus <b>(+)</b> symbol

### Complex Expressions

In [39]:
a = 3 + 5 - 6 * 2 / 4
a

5.0

## Challenge! Write the following to code

$$ g(z) = \frac{1}{1+e^{-z}}  $$

1) z = 8, and e = 2.718 should be equal to 0.9996643716832646

2) z = 2, and e = 2.718 should be equal to 0.8807753038918279

Hint: import numpy, and use numpy.exp

In [46]:
z = 8
e= 2.718

# Write your code here #
g = 1 / (1 + np.exp(-z))
# End of code #

print(g)

0.99966464987


In [23]:
import numpy as np


<b><i>TRIVIA</i></b>: The value <b>e</b>, also called <b>Euler's number</b>, is a mathematical constant representing an irrational number that is approximately <b>2.71828</b>. Irrational, meaning the constant <b>e</b> is a real number that is unending and is unable to accurately be represented as a fraction, similar to that of <b>pi</b>.

## D. Control Statements and Data Structures
## Conditional Statements
In Python, curly brackets are not used to designate that multiple commands are inside a conditional statement, instead uniform spacing is used. Please take note however that the composition of the uniform spacing must be the same, such that if 4 spaces are being used, even though 4 spaces may have a visually similar result as a tab, interchanging them would produce an error statement
### Boolean Condition

In [26]:
x = True
if x:
    print("var x is True")
else:
    print("var x is False")

var x is True


### String Condition

In [28]:
x = "Hello World! "

if x == 'Hello World!':
    print("var x is Hello World!")
else:
    print("var x is not Hello World!")

var x is not Hello World!


### Numerical Condition

In [30]:
x = 10

if x == '10':
    print("var x is a String")
elif x == 10:
    print("var x is an Integer")
else:
    print("var x is none of the above")
    
type(x)

var x is an Integer


int

### Multiple Conditions

In [58]:
x = 10

if x > 5 and x < 15 and x == 10:
    print("var x is really 10!")
else:
    print("var x is not really 10")

var x is really 10!


In [ ]:
x = 10

if x == 10 or x == 20:
    print("var x can be 10 or 20")
else:
    print("var x is not 10 nor 20")

In [31]:
if True ^ True: 
    print("True!")
elif True:
    print("second True")

second True


## E. Loops
Similar with that of Conditional Statements, commands within a loop are designated by having a uniform spacing.
### For Loops

In [63]:
range(5)

range(0, 5)

In [35]:
for v in range(0,10,2):
    print(v)

0
2
4
6
8


In [36]:
list(range(5))

[0, 1, 2, 3, 4]

<b>NOTE:</b> The command <b>range(0,5,2)</b> is equivalent to all numbers from 0 incremented by 2 until it reaches the number 5-1

In [39]:
[v**2 for v in range(0,5)]

# for v in range(0,5)
#     v



[0, 1, 4, 9, 16]

<b>NOTE:</b> range([start], stop, [step])

### While Loops

In [69]:
var = 0
while var < 5:
    print(var)
    var += 2

0
2
4


### Nested Loops

In [70]:
x = 0
while x < 5:
    for y in range(0, x):
        print(y, end='')
    x+=1
    print()


0
01
012
0123


Always take note that there should be a colon <b>(:)</b> on the line where one delcares the loop or condition

## F. More on Lists and Dictionaries

### Lists

In [53]:
pi = 3.14159
varList = [1, 2, 'A', 'B', 'Hello!', pi]
print(varList[0])

1


For some basic information regarding lists, this has been discussed on section B. Data Types and Variables.
You can chose to insert different datatypes in a single list.

In [50]:
varList

[1, 2, 'A', 'B', 'Hello!', 3.14159]

You may call the content of the list through indexing

In [51]:
varList.append('World!')
print(varList)
varList.clear()

[1, 2, 'A', 'B', 'Hello!', 3.14159, 'World!']


You may also append items in the list. The example above shows you that when you added a new list item, it would be added towards the end of list

In [80]:
len(varList)

8

You may obtain the number of elements in a list by calling the <b>len()</b> function

In [56]:
varList = [1,1,1,2,2,2,3]

In [58]:
varList.remove(2)
# varList.remove?
print(varList)

[1, 1, 1, 2, 3]


Initially <b>varList[5]</b> was called and the result was 3.14159, however when the <b>remove()</b> function was called, it iterates though the list looking for the first match then erases that value.

### Dictionaries

In [85]:
var = "Hello World!"
varDict = {'first' : 123, 2 : 'abc', '3' : var, 4:['lista', 'listb']}
print(varDict[4][0])

lista


### List Generators and Comprehension

Study the code below and see what it does:

In [60]:
def gen_num_up_to(n):
    num = 0
    while num < n:
        yield num
        num += 1

In [65]:
[v for v in gen_num_up_to(5)]


[0, 1, 2, 3, 4]

Right now it doesn't do much, but we know it's a generator. Let's see what its content look like.

In [90]:
varList = gen_num_up_to(10)

# This is list comprehension. 
print([var for var in varList])
# The expression inside print() generates an item 'var' for every item in 'varList'

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
# Python's range() function works similarly as gen_num_up_to 
varList = range(10)

print([var for var in varList])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [66]:
# We can modify gen_num_up_to to consider a starting number, and a stopping number
def gen_num_up_to(start, stop, step=1):
    num = start
    while num < stop:
        yield num
        num += step

varList = gen_num_up_to(0,20)
print([var for var in varList])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [67]:
# You may have noticed the 3rd parameter step. If you read the code, you can see that the step is the incrementor
# Right now the step is set to 0, try changing it
varList = gen_num_up_to(0, 20, 2)

print([var for var in varList])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [7]:
varList = range(0, 20, 2)
print([var for var in varList])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


## G. Slicing (aka accessing arrays in a more specific way)

In [73]:
varList = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [74]:
# Get everything from the 0th element up to 5th element [0,5)
varList[0:5]

[1, 2, 3, 4, 5]

In [86]:
# ... or, just
varList[:5]

[1, 2, 3, 4, 5]

In [87]:
# Get everything starting from the 5th index until the end

varList[5:]

[6, 7, 8, 9, 10]

In [88]:
np.array(varList[:-2])

array([1, 2, 3, 4, 5, 6, 7, 8])

When you see a negative a slice index, you can imagine that varList is looped. For visualization, let us see how it will look like repeated
```
array                                 [1, 2, 3, 4, 5, 6, 7, 8, 9,10]
index  ... -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ... 
```

When repeated/looped...

```
array  ...  4,  5,  6,  7,  8,  9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,  1,  2,  3,  4,  5,  6 ...
index  ... -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ...
```

Similarly, if the slice index is negative, you are implementing a modulo with the length of the array.

In [72]:
-2 % len(varList)

8

In [109]:
varList[2:-2]

[3, 4, 5, 6, 7, 8]

<b>NOTE</b> <i>list([start]: end : [
step])

In [110]:
varList[2:8:2]

[3, 5, 7]

In [ ]:
a = 1, b=2
a,b =b,a

print(a)
print(b)

## H. Functions

Functions use the following notation:

def <i>function_name</i>:<br>
<pre><i> input commands here </i></pre>

Here is a sample function. np.random.randint(a, [b]) outputs uniformly random values from $[a,b) $

In [ ]:
def remainder(n, m):
    while True:
        if n - m < 0:
            return n
        else:
            n = n - m

In [ ]:
remainder(10, 4)

## Challenge: Coin Flip
Create a function that simulates coin flips repeated n times. Make the function a generator with a parameter n for the number of coin flips. Use np.random.randint to simulate a coin flip.

After defining this function, output a list using a list comprehension similar to the above example.

In [94]:
n = 10
np.random.randint(2)

1

In [102]:
[np.random.randint(2) for x in range(5)]

[0, 1, 1, 1, 1]

In [140]:
def coin_flip(n):
    return [np.random.randint(2) for x in range(n)]

coin_flip(10)

[0, 1, 1, 0, 0, 0, 0, 0, 0, 0]

# Vectors and Matrices  Computation
In Python, you can use <b>NUMPY</b> or <b>np</b> through the use of <b>import numpy as np</b> in order to easily use functions for vectors and matrices.

In [103]:
import numpy as np
# this is really not necessary as we already did %pylab inline

In [143]:
# This is how you create an np.array()
np.array([1,2,3,4])

array([1, 2, 3, 4])

It may not look like anything now, but handling np arrays will have benefits which you will see later

In [104]:
# Instead of creating a list, create a numpy array from 0 -> 100
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

It's the same as just: 

In [105]:
a = np.arange(0,10,0.5)
# Thus, ar[(ray)(r)]ange 

In [114]:
a.shape

a = np.ones((10,2)) * 3
a

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

## Vector computations
### Vector to scalar

In [116]:
varArray = np.arange(0, 5)
print(varArray)


[0 1 2 3 4]


In [117]:
varArray*2 # You can't do this with Python lists!

array([0, 2, 4, 6, 8])

In [123]:
# Broadcasting!
print(varArray)
print(varArray + np.array([5] *5))
print(varArray + 5)

[0 1 2 3 4]
[5 6 7 8 9]
[5 6 7 8 9]


### Vector to vector: Dot Product

In [125]:
varArrayA = np.arange(0,5)
varArrayB = np.arange(5,10)

print(varArrayA)
print(varArrayB)

varArray.dot(varArrayB)

np.dot(varArrayA, varArrayB)
# alternatively, np.dot(varArray, varArrayB) will give you the same answer

[0 1 2 3 4]
[5 6 7 8 9]


80

### Vector to vector: Element-wise multiplication

In [127]:
print(varArrayA)
print(varArrayB)
print(varArrayA * varArrayB)
varArrayA * varArrayB

[0 1 2 3 4]
[5 6 7 8 9]
[ 0  6 14 24 36]


array([ 0,  6, 14, 24, 36])

## Matrix to Scalar: Element-wise multiplication

In [128]:
# Create a random matrix with shape (4,4)
mat_a = np.random.randint(0, 5, size=(4,4))
print(mat_a)

[[3 4 4 2]
 [3 4 3 0]
 [3 1 0 3]
 [4 3 4 3]]


In [129]:
mat_a * 2

array([[6, 8, 8, 4],
       [6, 8, 6, 0],
       [6, 2, 0, 6],
       [8, 6, 8, 6]])

## Matrix to Matrix: Matrix Multiplication 

In [130]:
mat_a **2

array([[ 9, 16, 16,  4],
       [ 9, 16,  9,  0],
       [ 9,  1,  0,  9],
       [16,  9, 16,  9]])

## Advanced Matrix Operations

In [132]:
np.linalg.eig(mat_a)

(array([ 10.81296611,  -2.40390181,  -0.62500422,   2.21593993]),
 array([[-0.55537133, -0.39190566,  0.62604967, -0.00804491],
        [-0.40554343, -0.22107745, -0.55957311, -0.70794774],
        [-0.36561323,  0.86382508,  0.23662633,  0.42905201],
        [-0.62723535, -0.22658542, -0.48882279,  0.56094531]]))

## Create a linear hypothesis function

Create a function that takes (1) a vector x, (2) a vector theta and (3) a scalar bias variable to output the score.

$$
score = b + \sum_j{(\theta_j * x_j)}
$$

$$
score = \theta_1 * average\_actor\_likes + bias
$$

In [138]:
b = 5
x = np.array([5,6,7,8,9])
theta = np.array([5,6,7,8,9])
x.shape

(5,)

In [141]:
np.sum(theta * x) + b

260

In [142]:
np.dot(theta, x) + b

260

In [143]:
x = np.reshape(x,(5,1))
theta = np.reshape(theta, (5,1))
x.shape

(5, 1)

In [56]:
# To do a matrix transform, append a .T
print(x)
print(x.T)

[[5]
 [6]
 [7]
 [8]
 [9]]
[[5 6 7 8 9]]


In [145]:
def linearregdot(theta, x, b):
    return np.dot(theta.T, x) + b
#                 (1x5) (5x1)

def linearregmult(theta, x, b):
    return np.sum(theta * x) + b

print("Via dot " , linearregdot(theta, x, b))
print("Via mult ", linearregdot(theta, x, b))

# Use np.squeeze to 
print(np.squeeze(linearregdot(theta, x, b)))

Via dot  [[260]]
Via mult  [[260]]
260


## Create an RMSE function
Create a function that compares two vectors and outputs the root mean squared error / deviation.

$$
\operatorname{RMSD}(\hat{\theta}) = \sqrt{\operatorname{MSE}(\hat{\theta})} = \sqrt{\operatorname{E}((\hat{\theta}-\theta)^2)}
$$

## Creating an array for random values

Random integer from 1 to 10

In [58]:
np.random.randint(1, 10)

5

Array of size (2,5) filled with random integers from 1 to 10

In [59]:
np.random.randint(1, 10, (2,5))

array([[2, 1, 8, 5, 1],
       [9, 8, 9, 2, 5]])

Array of size (2,3,4) filled with random values

In [61]:
np.random.rand(2,3,4)

array([[[ 0.65867374,  0.02514169,  0.92664794,  0.3190027 ],
        [ 0.74152544,  0.10426852,  0.16819306,  0.99867372],
        [ 0.6072753 ,  0.38439401,  0.81541447,  0.61535818]],

       [[ 0.95388243,  0.06359492,  0.50499025,  0.74917872],
        [ 0.07682553,  0.35185367,  0.70335701,  0.98782402],
        [ 0.93395231,  0.21702616,  0.74582793,  0.30096364]]])

## Array Indexing 

While this is not slicing, another form to access via **array indexing**

In [146]:
a = np.arange(1,20)

# Get only the elements from array 'a' whose index is inside array 'idx'
idx = [1,2,3]
print(a)
a[idx]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([2, 3, 4])

In [147]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [68]:
# Get indices of the array whose element is more than 5
idx = a > 5 
idx

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [70]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [149]:
print(a>5)
print(a<15)
print((a>5) & (a<15))

[False False False False False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True False False False False False]
[False False False False False  True  True  True  True  True  True  True
  True  True False False False False False]


In [72]:
a[(a>5) & (a<15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [161]:
matrixTmp = np.random.randn(5,3)
matrixTmp

array([[ 0.8701854 , -0.34223665, -0.24829506],
       [ 2.57992147, -0.40340791,  1.16062469],
       [-0.33818574,  1.12490079,  0.46500316],
       [-0.94150186,  0.1666294 , -0.70774856],
       [-0.50039519,  1.70772336, -1.1168813 ]])

In [162]:
matrixTmp[[0,1,2,3,4],[1,0,2,0,1]]

array([-0.34223665,  2.57992147,  0.46500316, -0.94150186,  1.70772336])

In [166]:
idxMax = np.argmax(matrixTmp, axis=1)
matrixTmp[np.arange(matrixTmp.shape[0]), idxMax]

array([ 0.8701854 ,  2.57992147,  1.12490079,  0.1666294 ,  1.70772336])

## Joining arrays

There are many cases where you need to combine arrays together. To do this, let's create two simple arrays with the same shape.

In [154]:
varArrayA = np.random.randint(0,10,(5,3))
varArrayB = np.random.randint(0,10,(5,3))

print(varArrayA)
print(varArrayB)

[[8 4]
 [3 9]
 [1 2]
 [8 7]
 [0 5]]
[[0 2]
 [6 5]
 [9 7]
 [9 0]
 [4 0]]


In [155]:
# Let's check the shape of the array varArrayA
varArrayA.shape

(5, 2)

In [156]:
# To access the first index of the shape tuple, type:
varArrayA.shape[0]
# These are the rows

5

In [157]:
# Now, to access the second index of the shape tuple, type:
varArrayA.shape[1]
# These are the columns

2

From 2 separate arrays with shapes (5,3), we want to combine this to a single array with the shape (10,3).

To join them, we can use `np.concatenate`

In [158]:
varArrayC = np.concatenate((varArrayA, varArrayB))
print(varArrayC)

[[8 4]
 [3 9]
 [1 2]
 [8 7]
 [0 5]
 [0 2]
 [6 5]
 [9 7]
 [9 0]
 [4 0]]


This looks great! Let's check the shape.

In [159]:
varArrayC.shape

(10, 2)

If you noticed, from (5,3) it became a (10,3). Below is another way of doing the same command:

In [160]:
varArrayC = np.concatenate((varArrayA, varArrayB), axis=0)
# axis here is 0, which indicate the shape tuple index that changed; therefore axis is 0
print(varArrayC)

[[8 4]
 [3 9]
 [1 2]
 [8 7]
 [0 5]
 [0 2]
 [6 5]
 [9 7]
 [9 0]
 [4 0]]


Now, let's try to join it into a single array with shape (5,6). Here, the default np.concatenate() will not work anymore.

The (5,3) shape will change into (5,6), thus changing the axis=1

In [88]:
varArrayC = np.concatenate((varArrayA, varArrayB),axis=1)
print(varArrayC)

[[1 5 9 0]
 [6 2 3 0]
 [6 6 8 2]
 [1 7 4 9]
 [8 2 8 3]]


There is also `np.stack`, which will add another axis instead of modifying the exising ones

In [115]:
# axis = 0
varArrayC=np.stack((varArrayA, varArrayB), axis=0)
varArrayC.shape
print(varArrayC)

[[[3 2 4]
  [7 7 1]
  [5 0 0]
  [9 4 8]
  [7 5 6]]

 [[8 3 9]
  [3 2 5]
  [3 3 6]
  [3 6 9]
  [6 0 7]]]


In [116]:
varArrayC.shape

(2, 5, 3)

In [125]:
varArrayC = np.stack((varArrayA, varArrayB), axis=1)
varArrayC.shape

(5, 2, 3)

In [124]:
varArrayC

array([[[3, 8],
        [2, 3],
        [4, 9]],

       [[7, 3],
        [7, 2],
        [1, 5]],

       [[5, 3],
        [0, 3],
        [0, 6]],

       [[9, 3],
        [4, 6],
        [8, 9]],

       [[7, 6],
        [5, 0],
        [6, 7]]])

In [126]:
varArrayC = np.stack((varArrayA, varArrayB), axis=2)
varArrayC.shape

(5, 3, 2)

<center>**fin**</center>